/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sustech_mse_simplecae_jni_Sample */

#ifndef _Included_sustech_mse_simplecae_jni_Sample
#define _Included_sustech_mse_simplecae_jni_Sample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sustech_mse_simplecae_jni_Sample
 * Method:    addPoint
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_sustech_mse_simplecae_jni_Sample_addPoint
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     sustech_mse_simplecae_jni_Sample
 * Method:    addLine
 * Signature: (DD)Z
 */
JNIEXPORT jboolean JNICALL Java_sustech_mse_simplecae_jni_Sample_addLine
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     sustech_mse_simplecae_jni_Sample
 * Method:    addCircle
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sustech_mse_simplecae_jni_Sample_addCircle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sustech_mse_simplecae_jni_Sample
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_sustech_mse_simplecae_jni_Sample_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
